### DISCUSSION TITLE
Github issue forms

### DISCUSSION THREAD

**Discussion by reinerh** [netblue30/firejail#4468] [Ideas]
I just noticed on a different project that Github now has support for custom issue forms.
An example can be seen here: https://github.com/CleverRaven/Cataclysm-DDA/issues/new?assignees=&labels=&template=bug_report.yaml

Documentation for that feature is here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

I think we could make our "new issue" page also more beautiful with these forms.

**Comment by rusty-snake** [comment]
As related note: I am in the process of revising our issue template and adding more templates. But the process has become somewhat stale so if anyone want to pick this up, here's my current state.

<details><summary>bug_report.md</summary>

```diff
--- a/.github/ISSUE_TEMPLATE/bug_report.md
+++ b/.github/ISSUE_TEMPLATE/bug_report.md
@@ -12,9 +12,8 @@ Write clear, concise and in textual form.
 - Describe the bug.
 - What did you expect to happen?
 
-**No profile and disabling firejail**
-- What changed calling `firejail --noprofile /path/to/program` in a terminal?
-- What changed calling the program by path (e.g. `/usr/bin/vlc`)?
+**No profile**
+- What changes calling `firejail --noprofile /path/to/program` in a terminal?
 
 **Reproduce**
 Steps to reproduce the behavior:
@@ -31,13 +30,14 @@ Steps to reproduce the behavior:
 Other context about the problem like related errors to understand the problem.
 
 **Checklist**
+ - [ ] The issues is caused by firejail (i.e running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
  - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
  - [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
  - [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
  - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.
+ - [ ] I can reproduce the issue without custom modifications (e.g. globals.local)
 
 
 <details><summary> debug output </summary>
```

</details>

<details><summary>feature_request.md</summary>

```markdown
---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''
---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```

</details>

<details><summary>config.yml</summary>

```yaml
blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/netblue30/firejail/discussions
    about: FIXME


https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
```

</details>
